import { StyleSheet } from 'react-native';
import { createCommonScreenStyleDefinitions } from '@theme/stylePresets';
import { AppTheme } from '@theme/types';

export function createStyles(theme: AppTheme) {
  const common = createCommonScreenStyleDefinitions(theme);

  return StyleSheet.create({
    ...common,
    scrollContent: {
      gap: 10,
      paddingBottom: 8,
    },
    card: {
      ...common.card,
      gap: 8,
    },
    summaryHeadRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      flexWrap: 'wrap',
    },
    statusBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: theme.radii.md,
      borderWidth: 1,
      borderColor: theme.colors.borderStrong,
      backgroundColor: theme.colors.accentMuted,
      alignSelf: 'flex-start',
    },
    badgeText: {
      color: theme.colors.textPrimary,
      fontWeight: '700',
      fontSize: 12,
    },
    stepRail: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    stepChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: theme.radii.md,
      backgroundColor: theme.colors.surfaceMuted,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    stepChipComplete: {
      borderColor: theme.colors.accent,
      backgroundColor: theme.colors.accentMuted,
    },
    stepChipCurrent: {
      borderColor: theme.colors.borderStrong,
      backgroundColor: theme.colors.navItemHoverBackground,
    },
    stepChipText: {
      color: theme.colors.textSecondary,
      fontWeight: '600',
      fontSize: 12,
    },
    stepChipStateText: {
      color: theme.colors.textPrimary,
    },
    problemRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderRadius: theme.radii.md,
      borderWidth: 1,
    },
    problemRowWarn: {
      borderColor: theme.colors.danger,
      backgroundColor: theme.colors.dangerSurface,
    },
    problemRowOk: {
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surfaceMuted,
    },
    problemWarnText: {
      color: theme.colors.danger,
      flex: 1,
    },
    problemOkText: {
      color: theme.colors.textSecondary,
      flex: 1,
    },
    updatesToolbar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      flexWrap: 'wrap',
    },
    filterGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    filterLabel: {
      color: theme.colors.textSecondary,
      fontWeight: '600',
      fontSize: 12,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    filterContainer: {
      minWidth: 170,
      position: 'relative',
      zIndex: 20,
    },
    filterButton: {
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.inputBackground,
      borderRadius: theme.radii.md,
      paddingHorizontal: 10,
      paddingVertical: 8,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    filterButtonPressed: {
      backgroundColor: theme.colors.surfaceMuted,
    },
    filterButtonText: {
      color: theme.colors.textPrimary,
      fontWeight: '600',
      fontSize: 13,
      flexShrink: 1,
    },
    filterDropdown: {
      position: 'absolute',
      top: 42,
      left: 0,
      right: 0,
      borderWidth: 1,
      borderColor: theme.colors.borderStrong,
      borderRadius: theme.radii.md,
      backgroundColor: theme.colors.surfaceElevated,
      padding: 4,
      gap: 2,
    },
    filterOption: {
      paddingHorizontal: 8,
      paddingVertical: 8,
      borderRadius: theme.radii.sm,
    },
    filterOptionActive: {
      backgroundColor: theme.colors.accentMuted,
    },
    filterOptionPressed: {
      backgroundColor: theme.colors.navItemHoverBackground,
    },
    filterOptionText: {
      color: theme.colors.textSecondary,
      fontSize: 13,
    },
    filterOptionTextActive: {
      color: theme.colors.textPrimary,
      fontWeight: '600',
    },
    updateRow: {
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: theme.radii.md,
      backgroundColor: theme.colors.surfaceMuted,
      overflow: 'hidden',
    },
    updateHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      paddingHorizontal: 10,
      paddingVertical: 10,
    },
    updateHeaderPressed: {
      backgroundColor: theme.colors.navItemHoverBackground,
    },
    updateHeaderMain: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      flex: 1,
      gap: 8,
      flexWrap: 'wrap',
    },
    updateStatusBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: theme.radii.sm,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
      alignSelf: 'flex-start',
    },
    updateTimestamp: {
      color: theme.colors.textMuted,
      fontSize: 12,
      fontWeight: '500',
    },
    updateBody: {
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
      paddingHorizontal: 10,
      paddingVertical: 10,
      gap: 6,
      backgroundColor: theme.colors.surface,
    },
    itemRow: {
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: theme.radii.md,
      backgroundColor: theme.colors.surfaceMuted,
      paddingHorizontal: 10,
      paddingVertical: 8,
      gap: 4,
    },
    itemTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      flexWrap: 'wrap',
    },
    itemStatusBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: theme.radii.sm,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
    itemBadgeText: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      fontWeight: '600',
    },
    rawPayload: {
      color: theme.colors.textSecondary,
      fontFamily: 'monospace',
      fontSize: 12,
      lineHeight: 18,
    },
  });
}
